apiVersion: v1
kind: PersistentVolume
metadata:
  name: elastic-search
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /home/docker/pv/elasticsearch
    type: ""
  storageClassName: manual
